### ISSUE TITLE
Como vamos criar pull requests se não é possível fazer fork do repositório?

### ISSUE THREAD

**Issue by luizcdc** [mata56-ic-ufba/caracterizacao#2]
"Cannot fork because forking is disabled".

Ao tentar apenas dar push o que obtenho é:
`remote: Repository not found.
fatal: repository 'https://github.com/mata56-ic-ufba/caracterizacao.git/' not found`

**Comment by Re44e** [comment]
Pois é pessoal, precisamos decidir como iremos trabalhar. Inclusive, caso o uso de branchs seja permitido, acredito que precisaremos definir um padrão de nomenclatura. Ex: <github_user> - <branch_name>

**Comment by christinaflachufba** [comment]
Correto. O acesso para criar forks foi concedido.
